### ISSUE TITLE
[]version-Command to check if there is a new version on the remote

### ISSUE THREAD

**Issue by YilianSource** [YilianSource/brackeys-bot#116]

**Comment by CodeMyst** [comment]
- [ ] Add a note that the versioning commands can only be run on a Linux machine, maybe in the future we could make this cross platform
- [ ] Add a note that `sudo chmod +x shell/update.sh` and `sudo chmod +x shell/checkversion.sh` should be run before running the bot, making these files executable.

**Comment by YilianSource** [comment]
Can the checks be performed dynamically? I don't know about the `chmod` stuff, but it can be detected if the OS is linux with `RuntimeInformation.IsOSPlatform(OSPlatform.Linux)`.

**Comment by CodeMyst** [comment]
Yeah I would guess so. And the `chmod` stuff you would only do if you're on Linux of course.
