### ISSUE TITLE
Giveaway based on activity

### ISSUE THREAD

**Issue by Duxez** [YilianSource/brackeys-bot#117]
To allow only active users (users that haven't just joined and not talked) to win. 
Measured by for example date joined and amount of messages sent

**Comment by YilianSource** [comment]
Is this necessary, since there are no further giveaways planned in near future?

**Comment by CodeMyst** [comment]
Closing this issue as we aren't planning any giveaway in the near future. If we ever talk about this again this issue should be reopened (or a new one created).
