### ISSUE TITLE
Make it so that dming the bot creates a new staff channel

### ISSUE THREAD

**Issue by Duxez** [YilianSource/brackeys-bot#122]
So that people don't have to DM us but still can get some private help, not that I think it's useful, but another server I'm in has it and it's cool.

**Comment by CodeMyst** [comment]
I have no clue what you mean by this :thinking: 
You DM the bot and it creates a new staff channel? :thinking: what?

**Comment by Duxez** [comment]
Someone DM's the bot, the bot creates a channel only staff can access with the persons message, we respond in the channel the bot responds in the dm to the person with our message.

**Comment by Duxez** [comment]
It being cool is the only reason I want it

**Comment by CodeMyst** [comment]
And it's intent is for users to ask staff questions about the server or programming / unity / game dev questions?

**Comment by Duxez** [comment]
Server

**Comment by Duxez** [comment]
I'm not helping people in DM's and I never will

**Comment by CodeMyst** [comment]
I see. It is cool but we don't get that many people DM-ing us that it would be worthwhile implementing it. Also adds another layer between people and us, making it not so personal.

Will wait for other's input before closing this.

**Comment by Duxez** [comment]
_Guess I'll have to keep my, you can't have cool things stance then_ Cause I can't have cool things :(

**Comment by YilianSource** [comment]
I agree that it is a cool feature, but it's a bit unnecessary. People (mostly) DM staff to get an answer to an immediate question, not to create a discussion with the staff team. If there *is* a point made that is of staff-wide attention significance, I would expect the targeted staff member to forward that to the others anyway.
