### ISSUE TITLE
Doing '[]giverole \' has no output

### ISSUE THREAD

**Issue by AquaXV** [YilianSource/brackeys-bot#133]
When users do '[]giverole \' the bot outputs nothing, when users do '[]giverole \\' it displays the help message for giverole

**Comment by MetalBreaker** [comment]
Discord.NET bug, I believe. '\' is an escape character, and the command fails.

**Comment by YilianSource** [comment]
Indeed, it's Discord.NET's parsing that is failing here. To be more exact: 
`ParseFailed: "Input text may not end on an incomplete escape."`.

If you feel like we should automatically trim incomplete escape sequences, feel free to suggest that!

**Comment by CodeMyst** [comment]
Looks like this changed. `[]giverole` outputs all the roles and teams and `[]giverole \` doesn't. It would be nice if `[]giverole \` also outputted all the roles and teams.

**Comment by YilianSource** [comment]
Looks like this can't really be fixed since that is expected behaviour from Discord.NET. We can't access a message's content without explicitly modifying it, therefore we can't "ignore" the incomplete escape sequence.

**Comment by CodeMyst** [comment]
I see. It's not a big deal then. Can we close this then?
