### ISSUE TITLE
Ability to archive channels

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#138]
The bot would go through a channel and get all messages and download the images and format it in a nice markdown format.

The file structure would look something like this in the end:
```
- channel-name/
    - assets/
    - index.md
```

The `assets` folder would contain all the images.

Since this will mainly be used to archive events submissions the main folder and the title of `index.md` would contain the date, something like this: `Event#1-17.11.2018-Submissions`

We could also specify that the archive type should be event submissions so the bot would also record how many votes a specific entry got.

In the end the folder should be compressed to a zip file and be stored on the computer of at least 2 staff members (at least some redundancy). No need for storing this on the server, it would just waste disk space.

An sample `index.md` file of an event submissions channel would look like this:

# Event #&#x2060;1 Submissions (17.11.2018. - 18.11.2018.)

* Spook#0453 (226645971222790146) - 17/11/2018

    yeet'd (If anyone wants better quality or something feel free to slap me) - Tribute to "Wisp" obviously :stuck_out_tongue: *(edited)*
    `![image1](assets/image1.png)`

    **Votes: 34**

* EnderElement#9581 (259517909695594500) - 18/11/2018

    Made a whole environment for this one and realised that the style of Last Gleam is the z-depth pass. Nice animation between light and dark and you could see the flame flickering in the distance. (If you want a larger version let me know, it can go up to 1600x700 in .mov format, the gif doesn't have the best quality) *(edited)*
    `![image2](assets/image2.gif)`

    **Votes: 33**

**NOTE: It should also support gif and video files**

**Comment by YilianSource** [comment]
The resulting archive will be zipped and attached to a message by the bot, to then be downloaded and saved locally.

**Comment by MetalBreaker** [comment]
Does Discord allow this? Is this respecting users' privacy?

**Comment by YilianSource** [comment]
Why wouldn't it? We are only archiving submissions that were **chosen** by them to be submitted.

**Comment by CodeMyst** [comment]
And the data is already publicly available

**Comment by MetalBreaker** [comment]
Still. People can edit and delete their messages if they've said something embarassing or incorrect.
You can't just collect personally identifiable data like that. However, if it'll only be used for the entry submissions channel, I think it's fine. I'd like you to explicitly tell people that by enrolling in an event, they agree to having their entry archived.
