### ISSUE TITLE
Should the commands be case sensitive?

### ISSUE THREAD

**Issue by Duxez** [YilianSource/brackeys-bot#156]
I feel like starting with a capital letter shouldn't be a problem.

**Comment by YilianSource** [comment]
You are contradicting yourself. You want them to be case-sensitive, but say that starting with a capital letter shouldn't be problem?

**Comment by Duxez** [comment]
I'm not tho I'm asking if they should be since currently they are but I feel like they shouldn't be

**Comment by YilianSource** [comment]
Issue found: only custom commands are currently case-sensitive.
