### ISSUE TITLE
Filter word usage

### ISSUE THREAD

**Issue by Duxez** [YilianSource/brackeys-bot#180]

**Comment by CodeMyst** [comment]
We agreed not to have a word filter for now.

**Comment by YilianSource** [comment]
Re-opening, because we agreed to log these banned words in the audit log channel.

**Comment by YilianSource** [comment]
The words that are to be filtered should be customizable at runtime.
If the bot detects a filtered word in a [sent] message, the message should be logged to a "filter-channel", and immediately be deleted afterwards. Staff can take further consequences from there.

Planned for 3.1.

**Comment by AquaXV** [comment]
One could argue we can have it create auto-infractions but not post those, if people ask about it we can see if they were flagged multiple times for that offense or optionally delete the infraction if we see fit.

(I will most certainly forget the words a specific person used after a few weeks)

**Comment by YilianSource** [comment]
Optionally we could also create a list of filtered words they used in the past, which can be checked by staff on demand.

**Comment by AquaXV** [comment]
Finished with PR https://github.com/YilianSource/brackeys-bot/pull/190
