### ISSUE TITLE
Don't allow some commands to be run in certain channels

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#187]

**Comment by Lukephos** [comment]
Some commands like []timeleft should only be allowed in the bot channel and for ones like timeleft the relevant channel. In that case being jam channels. How to go about informing that to the user is up to you, but at minimum this should stop people repeatedly using commands in channels like general in the middle of talks. It's a small change but at things like events or bot changes it'll help.

**Comment by YilianSource** [comment]
@CodeMyst Is this still required? If so, how should it be implemented on the user side?

**Comment by CodeMyst** [comment]
Honestly don't see much of a need in it. But it could still be implemented and be useful in other ways. Maybe you could make a system where every channel has a list of ignored modules. So we can set the auto paste thingy to ignore the collab channels.

**Comment by YilianSource** [comment]
The _auto paste thingy_ was fixed in #205 by adding a blacklist for that service.
The codeblock pasting service is a _service_, not a _module_, and is theoretically not tied to commands whatsoever.

So you would suggest white-/blacklisting entire modules instead of specific commands?

**Comment by CodeMyst** [comment]
Nah that's fine. Just used the wrong terminology.

This can be closed then I guess, I don't see a reason to not allow some commands to be run in #general for example, since the way we tell people they can't do that and confusion will result in the same amount of clutter anyway, imo.

**Comment by YilianSource** [comment]
My thoughts exactly.

Well, this is closed then, we can re-open if it comes up again in the future!
