### ISSUE TITLE
slowmode command

### ISSUE THREAD

**Issue by AquaXV** [YilianSource/brackeys-bot#189]
Add slowmode and/or serverslowmode commands in case of emergency. In case of serverslowmode make sure to store default slowmode to be able to restore slowmode (`slowmode 0` is slowmode off, `slowmode -1(?)` is restore previous).

**Comment by TheDutchMagikarp** [comment]
I also like the disable command 3vil added in their bot, which just disables message permissions for everyone except admins in all channels of the server.
enable would then of course enable it again

**Comment by AquaXV** [comment]
That event was my inspiration for this yes, I think a serverwide disable would probably be better than serverwide slowmode.
