### ISSUE TITLE
[FEATURE] display all infractions in audit log when a user is warned

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#224]
**Why do you want this feature? What is the problem?**
We can check for previous infractions automatically. Currently if you warn someone twice and you don't remember the user from before it'd go unnoticed.

**Describe the solution you'd like**
When you warn someone, in the audit log show the new infraction alongside old ones.

**Comment by AquaXV** [comment]
Added conditional field to audit log entry where historical infractions are printed if present.
The newly added infraction will not show up in the overview list, it will only show past infractions next to the summary of the new infraction.
