### ISSUE TITLE
[BUG] Massive codeblock threshold detection

### ISSUE THREAD

**Issue by Wokarol** [YilianSource/brackeys-bot#229]
**Describe the bug**
Threshold count tag of codeblock "```" even tho it should not

**Expected behavior**
Threshold should count characters only inside actual block (after first line to before closing tag)

**Comment by AquaXV** [comment]
Why is this a bug? Take the threshold config and add 6 to only count inside the codeblock.

**Comment by Wokarol** [comment]
You would have to add 8 to account for new lines. Also it would still count language tags like "cs"

**Comment by Wokarol** [comment]
Also, "just add 6" is a work around, and not a fix

**Comment by AquaXV** [comment]
Unfortunately then there is no way to count the inside only, what language will the user use? C#, CSharp, Py, Python, Java, JavaScript, HTML, CSS? Unless you feel like writing a regex which will match on any of them, or any input at all for that matter, we can't count inside only.
