### ISSUE TITLE
[FEATURE] Massive codeblock detection change

### ISSUE THREAD

**Issue by Wokarol** [YilianSource/brackeys-bot#230]
**Describe the bug**
Massive codeblock detection is based of character count

**Expected behavior**
Detection should be based of line count

**Why?**
In more accurately describes when codeblock is massive because massive codeblock can be described as "codeblock that takes to much space on the screen" so it matters vertically only

**Additional notes**
Threshold of around 30-45 lines should be fine

**Comment by AquaXV** [comment]
This is a feature request, not a bug.

**Comment by YilianSource** [comment]
We cannot base this on line count.

Line lengths are different between clients (web, desktop, mobile), OSs (windows, mac, android) and screen resolutions and scalings.

A limitation on line count would not be any more arbitrary than a limit on character count.

**Comment by Wokarol** [comment]
Character count is more often than not a miss. Yes, line count should be adjusted to count for wrapping. We can for example count long lines as 2.
