### ISSUE TITLE
[FEATURE] Temp muting while already muted should add on time

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#233]
**Why do you want this feature? What is the problem?**
If you for example temp mute someone for 10 seconds, and then 10 hours, after the 10 second mute runs out they will get unmuted and the 10hour mute won't work.

**Describe the solution you'd like**
Temp muting if someone is already temp muted should increase the time of the temp mute. And if someone is temp muted, and you perm mute they should be perm muted.

**Comment by AquaXV** [comment]
I would argue it (re)sets the mute tiner to the given time; when you mute you expect to mute for the given time. Not to add onto the time. This would be quite catastrophic if 4 staffmembers try to mute the same person at the same time for 5, 8, 7, and 10 hours.
