### ISSUE TITLE
[BUG] Error on pinging the bot

### ISSUE THREAD

**Issue by TheDutchMagikarp** [YilianSource/brackeys-bot#245]
**Describe the bug**
Bot returns an error when pinged.
(Command !433331899478441995> does not exist!)

**To Reproduce**
Steps to reproduce the behavior.

1. Ping the bot
2. See error message

**Expected behavior**
The bot either doesn't do anything.

**Additional context**
Error:
`Command !433331899478441995> does not exist!`
Is the same for all users,

**Comment by TheDutchMagikarp** [comment]
Apparently it only happens if the message has content other than the ping itself.

**Comment by YilianSource** [comment]
`433331899478441995` is the bot's ID. Will look into it sometime.
