### ISSUE TITLE
[BUG] pastemyst content encoding isn't right

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#248]
**Describe the bug**
 The current way to encode the pastemyst content is using UrlPathEncode but that for some reason doesn't encode all characters properly (for example, the % character doesn't get encoded). So if a message contains multiple % chars the message wont get pasted.

**To Reproduce**

Create a big codeblock which has a couple of sequential % chars in it.

**Expected behavior**

The codeblock gets properly pasted.

**Additional context**

Suggesting to use `Uri.EscapeDataString` instead as that covers all proper characters to be encoded.

**Comment by YilianSource** [comment]
@CodeMyst Is this closed by #269, using v2?

**Comment by CodeMyst** [comment]
yes it is!
