### ISSUE TITLE
[BUG] Non-escaped markdown allows hyperlinks in embed response

### ISSUE THREAD

**Issue by oliverbooth** [YilianSource/brackeys-bot#251]
**Describe the bug**
When a command isn't recognised, the bot echoes back the command exactly as it was written. As a consequence, hyperlinks can be created because the response is dumped into an embed object, which supports this. If someone discovered this, they could link to malicious sites in disguise, and then delete their original message to hide the evidence.

**To Reproduce**
Execute a command by using Markdown to create a hyperlink.

**Expected behavior**
The bot should escape markdown special characters so that the plain-text version of the input is written.

**Additional context**
`mailto:` links don't seem to cause this

**Screenshots**
![image](https://user-images.githubusercontent.com/1129769/87948817-1b01cb00-ca9d-11ea-94cc-11854c0edf9a.png)

![image](https://user-images.githubusercontent.com/1129769/87948787-0de4dc00-ca9d-11ea-85ee-b1bff5a12223.png)

**Comment by CodeMyst** [comment]
![image](https://user-images.githubusercontent.com/7966628/87949862-dbd87780-caa6-11ea-80f6-9f23bd759527.png)
you can also do stuff like this kek

**Comment by YilianSource** [comment]
Useful: https://discord.foxbot.me/docs/api/Discord.Format.html#Discord_Format_Sanitize_System_String_
