### ISSUE TITLE
[FEATURE] Discord .NET Version

### ISSUE THREAD

**Issue by ANF-Studios** [YilianSource/brackeys-bot#253]
**Why do you want this feature? What is the problem?**
Brackeys Bot is running Discord.Net v2.1.1. 

Which is not the latest Discord .Net v2.2.0, so can you upgrade it?

**Comment by YilianSource** [comment]
From what I can find there is no changelog (yet) for v2.2.0, so there is no reason for us to upgrade without reason.

**Comment by ANF-Studios** [comment]
Okay thanks xD
