### ISSUE TITLE
[FEATURE] Add Current Version in README.MD

### ISSUE THREAD

**Issue by ANF-Studios** [YilianSource/brackeys-bot#255]
**Why do you want this feature? What is the problem?**
The readme file could use a version in the [chart table](https://github.com/YilianSource/brackeys-bot#versioning).
**Describe the solution you'd like**
You can add the versions; if not there, at least somewhere

**Comment by YilianSource** [comment]
That's a nice idea, but unfortunately that would require us to update the README manually every time a new patch is written, which is something that is just not worth the effort.

**Comment by ANF-Studios** [comment]
Yes indeed true and I cannot come up with anything so I guess this issue must be closed.. So long issue #255
