### ISSUE TITLE
 error : Found invalid data while decoding. [C:\Users\dheer\brackeys-bot\src\BrackeysBot.sln][BUG]

### ISSUE THREAD

**Issue by billydevyt** [YilianSource/brackeys-bot#261]
**Describe the bug**
 error : Found invalid data while decoding. [C:\Users\dheer\brackeys-bot\src\BrackeysBot.sln]

**steps**
open command, use dotnet restore
you'll get : 
```
  Determining projects to restore...
C:\Program Files\dotnet\sdk\3.1.402\NuGet.targets(128,5): error : Found invalid data while decoding. [C:\Users\dheer\brackeys-bot\src\BrackeysBot.sln]
```
use dotnet build, you'll get: 
  
```
Determining projects to restore...
C:\Program Files\dotnet\sdk\3.1.402\NuGet.targets(128,5): error : Found invalid data while decoding. [C:\Users\dheer\brackeys-bot\src\BrackeysBot.sln]

Build FAILED.

C:\Program Files\dotnet\sdk\3.1.402\NuGet.targets(128,5): error : Found invalid data while decoding. [C:\Users\dheer\brackeys-bot\src\BrackeysBot.sln]
    0 Warning(s)
    1 Error(s)
```

Time Elapsed 00:00:08.36

**Expected behavior**
expected this would build the binary file

**Comment by YilianSource** [comment]
Sorry for the late response.

It works on my end. Do you have the latest version of the bot?

**Comment by billydevyt** [comment]
I fixed it by cleaning all packages and then restoring them, so now it's working fine

**Comment by YilianSource** [comment]
Awesome!
