### ISSUE TITLE
[BUG] bot always returns Command not found error

### ISSUE THREAD

**Issue by hemanth2410** [YilianSource/brackeys-bot#267]
I cloned this repo, I was hoping to work on some modifications, felt like testing once, I checked built in commands, and bot always returns command not found error.
![error](https://user-images.githubusercontent.com/24288422/99353380-618bf880-28ca-11eb-80d9-71fb98ab17e9.PNG)

**Comment by CodeMyst** [comment]
have you enabled all the modules? i think you enable modules with `[]module enable <modulename>`

**Comment by hemanth2410** [comment]
oh ok 
i didnt do that sorry

**Comment by YilianSource** [comment]
All good, we should probably mention this in the README somewhere. I'll leave this open until we do!

**Comment by hemanth2410** [comment]
one last error, every command works except mute and tempmute

![mute wont work](https://user-images.githubusercontent.com/24288422/99531440-bf9f0580-29c8-11eb-8739-462568011ab1.PNG)

and here is the error displayed in console

![error trace](https://user-images.githubusercontent.com/24288422/99531923-7ac79e80-29c9-11eb-9bc4-5a9a7b33e3e9.PNG)

**Comment by YilianSource** [comment]
I believe this is an issue with bot intents.

Discord, recently and silently, introduced priviliged gateway intents, probably to reduce potential traffic on their end.  
To turn the required intent on, navigate to your developer panel, and select your application.  
In the Bot tab, check that the *Server Members Intent* is on.

![image](https://user-images.githubusercontent.com/41469451/99532229-41c90300-29a4-11eb-97dc-67e4e238e2f4.png)

Let me know if this fixes your issue!

**Comment by hemanth2410** [comment]
same error

![error same](https://user-images.githubusercontent.com/24288422/99532746-c9296d00-29ca-11eb-9b29-39ab0065ff1c.PNG)


object reference not set to instance

**Comment by hemanth2410** [comment]
sorry, looks like i need to add Role ID's to yaml file


i am doing it now
