### ISSUE TITLE
[FEATURE] Add a nopublic command which explains when to use them, and when to not

### ISSUE THREAD

**Issue by DaRealBerlm** [YilianSource/brackeys-bot#279]
**Why do you want this feature? What is the problem?**
Almost everyone following brackeys tutorials ends up with a habit of using public variables _everywhere_, especially to show in the inspector, which leads to bad code.

**Describe the solution you'd like** 
An informative command, that will explain why public variables should not be used _just_ to show a value in the inspector. It will talk about why public variables make maintaining code harder, and also how to use `[SerializeField]`. Also maybe say that properties should be used for public fields, to begin with.

**Comment by YilianSource** [comment]
Hey there, commands like this are implemented as custom commands during runtime, not as a backend implemenation, hardcoded in the source code.

Feel free to place this suggestion in the `#server-suggestions` in the Brackeys Community Discord server.
