### ISSUE TITLE
Advanced moderation features

### ISSUE THREAD

**Issue by MetalBreaker** [YilianSource/brackeys-bot#46]
Advanced moderation features that will be fine tuned to our staff's needs, and remove reliance on third party bots, which means we can stay fully operational even when they are down.

**Comment by CodeMyst** [comment]
We don't really need this kind of stuff. Closing for now.

**Comment by CodeMyst** [comment]
Reopening to get an opinion from @YilianSource

**Comment by AquaXV** [comment]
Please provide specific examples of functionality you would like to see implemented.
I agree with the argument for this suggestion.

**Comment by YilianSource** [comment]
I agree that a certain degree of moderation features would prove quite useful. Nothing hyper-advanced, but things like warning, banning, kicking, clearing messages, etc.
Before work in this should be started, a full list of features should be made, and divided up into issues.
I also propose that the `Commands` namespace should then also be broken down into a sub-namespace `Moderation`.
