### ISSUE TITLE
[]points <user> command should be an embed on return. 

### ISSUE THREAD

**Issue by Naggerknife** [YilianSource/brackeys-bot#52]

**Comment by Duxez** [comment]
I mean I don't really see why that'd be required? _Please change my mind LUL_

**Comment by Naggerknife** [comment]
Bot returns look so much better as embeds. Helps distinguish between a bot and user IMO. If nobody like it then it is what it is :)

**Comment by Duxez** [comment]
I agree that they look better but I don't necessarily feel like a simple message like the []points command should be embedded
