### ISSUE TITLE
Moderation features checklist

### ISSUE THREAD

**Issue by MetalBreaker** [YilianSource/brackeys-bot#54]
Planned moderation features that should be added in the `BrackeysBot.Commands.Moderation` namespace.

- [x] Kicking
- [x] Banning
- [x] Infractions of varying severity
- [x] Clearing messages
- [x] Mute (timed and manual)

**Comment by YilianSource** [comment]
Features sound good so far. Only the points "Infractions of varying severity", "Consequences corresponding to the infractions" need further clarification, then we'll work on it.

**Comment by CodeMyst** [comment]
Infractions can be added manually. And it can be detected automatically in some cases.
Maybe spamming, mass mentioning.. can be detected automatically and would result in a warning.

3 warnings would mean a kick. 5 warnings is a ban.

**Comment by YilianSource** [comment]
So infractions as a counter, and certain criteria for gaining infractions, on a various seriousness level? Sounds great to me.

**Comment by MetalBreaker** [comment]
I'm working on this.

**Comment by CodeMyst** [comment]
@MetalBreaker I can't assign someone who's not a collaborator.

_Sent from my Galaxy J5(2016) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ilijaivanov** [comment]
It's been done before, are you sure?

**Comment by CodeMyst** [comment]
Huh, weird. The app I'm using for GitHub doesn't allow me that. But I can do it from the desktop website.

**Comment by YilianSource** [comment]
@MetalBreaker When are you going to finish the moderation features?

**Comment by MetalBreaker** [comment]
On the weekend. Sorry, I haven't had much time since school began.

**Comment by YilianSource** [comment]
When will this approximately be finished?
Also, can you add Audit Log entries for the moderation features?

**Comment by MetalBreaker** [comment]
I'm on vacation till the 3rd. On the 3rd and 4th I won't have school so I'll have free time. Sorry for not finishing it earlier. I'll see what I can do.
