### ISSUE TITLE
Remove the job checking system

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#78]

**Comment by MetalBreaker** [comment]
Why?

**Comment by Duxez** [comment]
Because it's way too strict.

**Comment by MetalBreaker** [comment]
What do you mean? It's not. It's just not very forgiving with misspellings. I've already pretty much relaxed it quite a bit, allowing additional information etc

**Comment by CodeMyst** [comment]
They are, since people in the real world won't simply copy / paste the template file. So it's much easier for me to go through the channels a couple of times a day than to get messages from people who don't know why they can't post in those channels and then I have to investigate why. It's just easier for everyone if it is removed.

**Comment by Duxez** [comment]
"It's just not very forgiving with misspellings" Which means it's way to strict. We're an international server, not everyone reads everything. And misspellings are too likely to happen. As well as the fact that there were some issues that we couldn't even figure out.

**Comment by MetalBreaker** [comment]
"Not everyone reads everything", which means they shouldn't be posting a job offer anyway.
If they want to post a job offer, they should at least learn basic business English. This isn't brain surgery.
However, maybe it'd just be easier for the moderators to hand inspect the messages. Though, there is a thing called the Levenshtein distance, which could be used for cutting 4-5 typos some slack.

**Comment by CodeMyst** [comment]
The feature will be removed as it's easier for us to manually check in the channels than to create a proper system which will require 0 monitoring from us. Locking the conversation for now.
